services:
  - type: web
    name: bingo-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && cd frontend && npm install && npm run build && mkdir -p ../backend/static && cp -r dist/* ../backend/static/
    startCommand: cd backend && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
    healthCheckPath: /docs